id: allow-failure
namespace: io.kestra.tests

inputs:
  - name: crash
    type: STRING

tasks:
  - id: first
    type: io.kestra.core.tasks.flows.Sequential
    tasks:
      - id: 1-1-allow-failure
        type: io.kestra.core.tasks.flows.AllowFailure
        tasks:
          - id: 1-1-1_seq
            type: io.kestra.core.tasks.flows.Sequential
            tasks:
              - id: 1-1-1-1
                type: io.kestra.core.tasks.debugs.Return
                format: "{{task.id}} > {{taskrun.startDate}}"
              - id: ko
                type: io.kestra.core.tasks.executions.Fail
              - id: 1-1-1-3
                type: io.kestra.core.tasks.debugs.Return
                format: "{{task.id}} > {{taskrun.startDate}}"
        errors:
          - id: local-error
            type: io.kestra.core.tasks.debugs.Return
            format: "Error Trigger ! {{task.id}}"
      - id: 1-2-todo
        type: io.kestra.core.tasks.debugs.Return
        format: "{{task.id}} > {{taskrun.startDate}}"
  - id: switch
    type: io.kestra.core.tasks.flows.Switch
    value: "{{ inputs.crash is defined }}"
    cases:
      "true":
        - id: crash
          type: io.kestra.core.tasks.executions.Fail
    defaults:
      - id: last
        type: io.kestra.core.tasks.debugs.Return
        format: "{{task.id}} > {{taskrun.startDate}}"


errors:
  - id: global-error
    type: io.kestra.core.tasks.debugs.Return
    format: "Error Trigger ! {{task.id}}"